<?php

require ('client.php');

try {

    $address = [
        'street'       => 'Rua Guilhermina Guinle',
        'number'       => '272',
        'complement'   => 'Some information',
        'neighborhood' => 'Boatafogo',
        'city'         => 'Rio de Janeiro',
        'state'        => 'RJ',
        'country'      => 'BR',
        'zip_code'     => '22270060',
        'metadata'     => [
            'address_attr' => 'data'
        ]
    ];

    $homePhone = [
        'country_code' => '55',
        'area_code'    => '21',
        'number'       => '55554444'
    ];

    $mobilePhone = [
        'country_code' => '55',
        'area_code'    => '21',
        'number'       => '988887777'
    ];

    $phones = [
        'home_phone'   => $homePhone,
        'mobile_phone' => $mobilePhone
    ];

    $customer = [
        'address'   => $address,
        'phones'    => $phones,
        'code'      => 'CUSTOMER_INTEGRATION_CODE',
        'type'      => 'individual',
        'name'      => 'Fabiano Couto',
        'email'     => 'fabianocouto@domain.com',
        'document'  => '34435132630', // Generated by https://www.geradordecpf.org/
        'gender'    => 'male',
        'birthdate' => '1982-06-03',
        'metadata'  => [
            'customer_attr' => 'data'
        ]
    ];

    $creditCard = [
        'number'      => '30513940605542', // Generated by https://names.igopaygo.com/credit-card
        'holder_name' => 'Fabiano Couto',
        'exp_month'   => '05',
        'exp_year'    => '2021',
        'cvv'         => '038',
        'metadata'    => [
            'card_attr' => 'data'
        ]
    ];

    $creditCardPayment = [
        'capture'              => false, // true for auth and capture
        'installments'         => 1,
        'statement_descriptor' => 'Credit Card Payment',
        'card'                 => $creditCard,
    ];

    $payment = [
        'payment_method' => 'credit_card',
        'credit_card'    => $creditCardPayment,
        'metadata'       => [
            'payment_attr' => 'data'
        ]
    ];

    // $bankSlip = [
    //     'bank' => 341,
    //     'instructions' => 'Favor, não receber após o vencimento.',
    //     'due_at'       => date('Y-m-d', strtotime('+5 days')),
    //     'metadata'     => [
    //         'bank_slip_attr' => 'data',
    //     ]
    // ];

    // $payment = [
    //     'payment_method' => 'boleto',
    //     'boleto'         => $bankSlip,
    //     'metadata'       => [
    //         'payment_attr' => 'data'
    //     ]
    // ];

    $request = [
        'code'      => 'CHARGE_INTEGRATION_CODE',
        'amount'    => '100', // In cents
        'currency'  => 'BRL',
        'due_at'    => date('Y-m-d H:i:s', time()),
        'customer'  => $customer,
        'payment'   => $payment,
        'metadata'       => [
            'charge_attr' => 'data'
        ]
    ];

	$response = $client->request('POST', 'charges', ['json' => $request]);

    $result = json_decode($response->getBody());

	DumpData($result);

} catch (Exception $e) {

	DumpData($e);
}