<?php

require ('client.php');

try {

    // CUSTOMER

    $createAddressRequest = new MundiAPILib\Models\CreateAddressRequest();
    $createAddressRequest->street       = 'Rua Guilhermina Guinle';
    $createAddressRequest->number       = '272';
    $createAddressRequest->complement   = 'Some information';
    $createAddressRequest->neighborhood = 'Boatafogo';
    $createAddressRequest->city         = 'Rio de Janeiro';
    $createAddressRequest->state        = 'RJ';
    $createAddressRequest->country      = 'BR';
    $createAddressRequest->zipCode      = '22270060';
    $createAddressRequest->metadata     = ['address_attr' => 'data'];

    $createHomePhoneRequest = new MundiAPILib\Models\CreatePhoneRequest();
    $createHomePhoneRequest->countryCode = '55';
    $createHomePhoneRequest->areaCode    = '21';
    $createHomePhoneRequest->number      = '55554444';

    $createMobilePhoneRequest = new MundiAPILib\Models\CreatePhoneRequest();
    $createMobilePhoneRequest->countryCode = '55';
    $createMobilePhoneRequest->areaCode    = '21';
    $createMobilePhoneRequest->number      = '988887777';

    $createPhonesRequest = new MundiAPILib\Models\CreatePhonesRequest();
    $createPhonesRequest->homePhone   = $createHomePhoneRequest;
    $createPhonesRequest->mobilePhone = $createMobilePhoneRequest;

	$createCustomerRequest = new MundiAPILib\Models\CreateCustomerRequest();
    $createCustomerRequest->address     = $createAddressRequest;
    $createCustomerRequest->phones      = $createPhonesRequest;
    $createCustomerRequest->code        = 'CUSTOMER_INTEGRATION_CODE';
    $createCustomerRequest->type        = 'individual';
    $createCustomerRequest->name        = 'Fabiano Couto';
    $createCustomerRequest->email       = 'fabianocouto@domain.com';
    $createCustomerRequest->document    = '34435132630'; // Generated by https://www.geradordecpf.org/
    $createCustomerRequest->gender      = 'male';
    $createCustomerRequest->birthdate   = '1982-06-03';
    $createCustomerRequest->metadata    = ['customer_attr' => 'data'];

    // DUE DATE

    $dueDate = new DateTime('now');
    $dueDate->add(new DateInterval('P5D')); // Add 5 days

    // CREDIT CARD

    $createCardRequest = new MundiAPILib\Models\CreateCardRequest();
    $createCardRequest->number     = '30513940605542'; // Generated by https://names.igopaygo.com/credit-card
    $createCardRequest->holderName = 'Fabiano Couto';
    $createCardRequest->expMonth   = '08';
    $createCardRequest->expYear    = '2021';
    $createCardRequest->cvv        = '038';

    $createCreditCardPaymentRequest = new MundiAPILib\Models\CreateCreditCardPaymentRequest();
    $createCreditCardPaymentRequest->card         = $createCardRequest;
    $createCreditCardPaymentRequest->installments = 1;
    $createCreditCardPaymentRequest->capture      = true; // true for auth and capture

    $createPaymnentRequest = new MundiAPILib\Models\CreatePaymentRequest();
    $createPaymnentRequest->creditCard    = $createCreditCardPaymentRequest;
    $createPaymnentRequest->paymentMethod = 'credit_card';
    $createPaymnentRequest->metadata      = ['payment_attr' => 'data'];

    // BANK SLIP

    // $createSlipPaymentRequest = new MundiAPILib\Models\CreateBoletoPaymentRequest();
    // $createSlipPaymentRequest->bank         = '341';
    // $createSlipPaymentRequest->instructions = 'Favor, não receber após o vencimento.';
    // $createSlipPaymentRequest->dueAt        = $dueDate;
    // $createSlipPaymentRequest->metadata     = ['slip_attr' => 'data'];

    // $createPaymnentRequest = new MundiAPILib\Models\CreatePaymentRequest();
    // $createPaymnentRequest->boleto = $createSlipPaymentRequest;
    // $createPaymnentRequest->paymentMethod = 'boleto';
    // $createPaymnentRequest->metadata      = ['payment_attr' => 'data'];

    // CHARGE

	$createChargeRequest = new MundiAPILib\Models\CreateChargeRequest();
	$createChargeRequest->customer = $createCustomerRequest;
	$createChargeRequest->payment  = $createPaymnentRequest;
    $createChargeRequest->code     = 'CHARGE_INTEGRATION_CODE'; // If not informed, a random code is generated
    $createChargeRequest->dueAt    = $dueDate;
	$createChargeRequest->currency = 'BRL';
	$createChargeRequest->amount   = 100;  // In cents
    $createChargeRequest->metadata = ['charge_attr' => 'data'];

	$charges = $client->getCharges();

	$result = $charges->createCharge($createChargeRequest);

	DumpData($result);

} catch (Exception $e) {

	DumpData($e);
}